2022-05-09 08:40:38,842 ERROR [/Users/hideakiehara/virtualenv/dj06/ClassBasedView/ClassBasedView/middleware.py:14] This name is invalid.
Traceback (most recent call last):
  File "/Users/hideakiehara/virtualenv/dj06/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hideakiehara/virtualenv/dj06/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/hideakiehara/virtualenv/dj06/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/hideakiehara/virtualenv/dj06/lib/python3.7/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/Users/hideakiehara/virtualenv/dj06/ClassBasedView/store/views.py", line 49, in get_context_data
    raise Http404("This name is invalid.")
django.http.response.Http404: This name is invalid.
